[project]
name = "aws_key_rotate"
version = "0.1.1"
description = "Rotate your AWS access keys and update your credentials file."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3"
]

[project.scripts]
aws_key_rotate = "aws_key_rotate.cli:main"

